### ISSUE TITLE
Resources are created in OCI but failing in creating sessions in bastion service

### ISSUE THREAD

**Issue by gpitchai** [oracle-quickstart/oci-arch-cassandra#1] opened 2022-01-18 17:55 UTC
Following error message is displayed.

module.cassandra.module.cassandra-node.null_resource.remote-exec-scripts-with-bastion-service[4] (remote-exec): + sudo service cassandra start

module.cassandra.module.cassandra-node.null_resource.remote-exec-scripts-with-bastion-service[4] (remote-exec): Reloading systemd:

module.cassandra.module.cassandra-node.null_resource.remote-exec-scripts-with-bastion-service[4] (remote-exec): [60G[[0;32m  OK  [0;39m]

module.cassandra.module.cassandra-node.null_resource.remote-exec-scripts-with-bastion-service[4] (remote-exec): Starting cassandra (via systemctl):

module.cassandra.module.cassandra-node.null_resource.remote-exec-scripts-with-bastion-service[4] (remote-exec): [60G[[0;32m  OK  [0;39m]

module.cassandra.module.cassandra-node.null_resource.remote-exec-scripts-with-bastion-service[4]: Creation complete after 1m57s [id=4391607024434533051]

Error: remote-exec provisioner error

  with module.cassandra.module.cassandra-node.null_resource.remote-exec-scripts-with-bastion-service[1],

  on .terraform/modules/cassandra/modules/cassandra-node/main.tf line 158, in resource "null_resource" "remote-exec-scripts-with-bastion-service" 

 158:   provisioner "remote-exec" {

error executing "/tmp/terraform_1649746403.sh": Process exited with status 1

Error: remote-exec provisioner error

  with module.cassandra.module.cassandra-node.null_resource.remote-exec-scripts-with-bastion-service[0],

  on .terraform/modules/cassandra/modules/cassandra-node/main.tf line 158, in resource "null_resource" "remote-exec-scripts-with-bastion-service" 

 158:   provisioner "remote-exec" {

error executing "/tmp/terraform_915489618.sh": Process exited with status 1

Error: remote-exec provisioner error

  with module.cassandra.module.cassandra-node.null_resource.remote-exec-scripts-with-bastion-service[3],

  on .terraform/modules/cassandra/modules/cassandra-node/main.tf line 158, in resource "null_resource" "remote-exec-scripts-with-bastion-service" 

 158:   provisioner "remote-exec" {

error executing "/tmp/terraform_92942908.sh": Process exited with status 1

Error: remote-exec provisioner error

  with module.cassandra.module.cassandra-node.null_resource.remote-exec-scripts-with-bastion-service[5],

  on .terraform/modules/cassandra/modules/cassandra-node/main.tf line 158, in resource "null_resource" "remote-exec-scripts-with-bastion-service" 

 158:   provisioner "remote-exec" {

error executing "/tmp/terraform_2124213345.sh": Process exited with status 1

Error: remote-exec provisioner error

  with module.cassandra.module.cassandra-node.null_resource.remote-exec-scripts-with-bastion-service[2],

  on .terraform/modules/cassandra/modules/cassandra-node/main.tf line 158, in resource "null_resource" "remote-exec-scripts-with-bastion-service" 

 158:   provisioner "remote-exec" {

error executing "/tmp/terraform_143960291.sh": Process exited with status 1

**Comment by lfeldman** [comment] 2022-01-19 15:59
@gpitchai I am afraid I am not able to reproduce your issue. On my side, everything went smoothly. Could you repeat the deployment:

![image](https://user-images.githubusercontent.com/19390609/150167833-25022eb8-24dc-41b7-bdb0-cb0f78fe6af2.png)

**Comment by lfeldman** [comment] 2022-01-20 16:52
@gpitchai Let me close this issue as there is no feedback. Please let me know and we can re-open it later.

**Closed as completed by lfeldman** 2022-01-20 16:52 UTC
